### ISSUE TITLE
Handle text is rendered for empty columns with in-place editing

### ISSUE THREAD

**Issue by awieland** [activescaffold/active_scaffold#222]
I don't understand the purpose of this CSS from  2ab1aadd1806893ed02d9499cc4a41f6ded2a747:

``` css
.active-scaffold tbody.records td.in_place_editor_field.empty .handle {
display:inline;
}
```

The `display:inline` overrides `display:none`, causing the text for an empty column to be prefixed with "--". For example, if `config.list.empty_field_text = '(none)'`, then I see "--(none)".
