### ISSUE TITLE
Is it possible to freeze the actions column so with large tables we do not have to scroll to the right?

### ISSUE THREAD

**Issue by msincan** [activescaffold/active_scaffold#534]
Hi,

Since this is my first post, I would like to start by thanking the developers and contributors for maintaining this great project. We are using active scaffold with large models that have many tens of columns and it sometimes is quite challenging to scroll to the right to get to the action links. Is it possible to configure active scaffold so that the action links always stay at the right end of the screen and we only scroll sideways for the data columns while the action links are stationary/fixed at the right?

**Comment by scambra** [comment]
If doable, it should be done with CSS.
You could try setting position: fixed to td.actions, but it will hide columns at right, so probably you should hide actions and display them only when cursor is over row for example. You can start with this CSS and try different styles:

```css
.active-scaffold tr.record td.actions {
    position: fixed;
    right: 0;
    display: none;
}
.active-scaffold tr.record:hover td.actions {
    display: table-cell;
}
```

For this kind of questions, it's better ask to activescaffold google group, other users could help you:
https://groups.google.com/forum/#!forum/activescaffold
