### ISSUE TITLE
List Width

### ISSUE THREAD

**Issue by deep021985** [activescaffold/active_scaffold#607]
I have only two columns which occupies entire screen. Is there any way to reduce the width of list table through config or helper. I was trying to override the the list through _list.erb but here I have to rewrite the whole CSS and JavaScript again for this small issue.

**Comment by scambra** [comment]
To change appearance you don't have to overwrite views or helpers, only change with CSS, e.g.

```css
.active-scaffold.<controller-name>-view table {
  width: auto;
}
```
